#https://hub.docker.com/r/microsoft/dotnet/

FROM microsoft/aspnetcore:2.0
WORKDIR /dotnetapp
Copy . /dotnetapp
VOLUME /dotnetapp/sqlite
ENV ASPNETCORE_URLS http://*:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "YuukoBlog.dll"]
